name: ronalderg_util
description: "Una colección de utilidades y validadores para proyectos de Flutter."
version: 0.0.1
homepage: https://github.com/ronalderg/ronalderg_util

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
